In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split,GridSearchCV

In [2]:
data = pd.read_csv('C:/Users/prate/Downloads/glass.csv')

In [3]:
x = data.drop('Type',axis = 1)
y = data.Type

In [4]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3)

In [5]:
svm1 = SVC(kernel='linear')
svm1.fit(xtrain,ytrain)

SVC(kernel='linear')

In [6]:
ypred = svm1.predict(xtest)
ypred

array([1, 1, 2, 2, 1, 3, 2, 1, 3, 3, 3, 2, 6, 5, 2, 5, 2, 7, 2, 2, 3, 2,
       6, 2, 1, 2, 1, 1, 6, 1, 2, 1, 2, 6, 3, 2, 1, 2, 2, 6, 1, 7, 2, 2,
       5, 1, 2, 5, 2, 2, 2, 7, 7, 7, 1, 1, 2, 7, 1, 1, 2, 1, 2, 1, 2],
      dtype=int64)

In [7]:
print(accuracy_score(ytest,ypred))

0.9846153846153847


In [8]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        26
           3       0.83      1.00      0.91         5
           5       1.00      0.80      0.89         5
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00         6

    accuracy                           0.98        65
   macro avg       0.97      0.97      0.97        65
weighted avg       0.99      0.98      0.98        65



In [9]:
print(confusion_matrix(ytest,ypred))

[[18  0  0  0  0  0]
 [ 0 26  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  1  4  0  0]
 [ 0  0  0  0  5  0]
 [ 0  0  0  0  0  6]]


In [11]:
model1 = SVC(kernel='sigmoid',gamma = 0.001)
model2 = SVC(kernel='poly',degree=0.3)
model3 = SVC(kernel='rbf')

model1.fit(xtrain,ytrain)
model2.fit(xtrain,ytrain)
model3.fit(xtrain,ytrain)

ypred1 = model1.predict(xtest)
ypred2 = model2.predict(xtest)
ypred3 = model3.predict(xtest)

print(accuracy_score(ytest,ypred1))
print(accuracy_score(ytest,ypred2))
print(accuracy_score(ytest,ypred3))

0.27692307692307694
0.27692307692307694
0.7384615384615385


In [13]:
grid_params = [{'kernel':['linear'],'C':[1,10,100,1000]},
                {'kernel':['rbf'],'gamma':[1e-3,1e-4],'C':[1,10,100,1000]},
              {'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]},
               {'kernel':['sigmoid'],'gamma':[1e-3,1e-4,1e-5],'C':[1,10,100,1000]}]

In [15]:
svm_model1 = GridSearchCV(SVC(),grid_params,cv=5)
svm_model1.fit(xtrain,ytrain)

C:\Users\prate\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'degree': [2, 3, 4], 'gamma': [0.001, 0.0001],
                          'kernel': ['poly']},
                         {'C': [1, 10, 100, 1000],
                          'gamma': [0.001, 0.0001, 1e-05],
                          'kernel': ['sigmoid']}])

In [16]:
print("best score", svm_model1.best_score_,'\n')
print("best C ",svm_model1.best_estimator_.C,'\n')
print("best gamma",svm_model1.best_estimator_.gamma,'\n')
print("best kernel",svm_model1.best_estimator_.kernel,'\n')

best score 0.9866666666666667 

best C  10 

best gamma 0.001 

best kernel rbf 



In [ ]:
final_model = svm_model1.best_estimator_

final_model.fit(xtrain,ytrain)
ypred = final_model(xtest)
